### PR TITLE
Waffles for 5 and 6

### PR DESCRIPTION
**Pull request by RCruzGil**
Waiting for the rest

### CODE REVIEW

**Review by rodrigovaldes — APPROVED** [review]
Cool! Hey, for the next time, maybe we can create a waffle function to avoid repeating code. However, this is not necessary at all. Everything is starting to make sense!

**Comment by rodrigovaldes** [comment]
Add waffles 5 and 6.

**Comment by rodrigovaldes** [comment]
@RCruzGil Idk if we want to preserve the indication of 1 square = 1%. Does this make the user count each square? Then, will they have a very clear idea about the number? 

I think we might want to evaluate the first impressions. I mean, without considering the possibility of counting the squares. What do you think?

**Comment by RCruzGil** [comment]
Yeah, I was also wondering about the indication, but I’m happy to take it out if needed.

**Comment by beauremus** [comment]
Should the squares be a real number rather than a percentage?

**Comment by rodrigovaldes** [comment]
It depends on the context. But I believe we need to guide users not to count the squares.

**Pull request merged**
